all:mymatch.o frac.o myvector.o
	gcc hw0201.c mymatch.o -lm -o hw0201
	gcc hw0202.c -lm -o hw0202
	gcc hw0204.c frac.o -lm -o hw0204
	gcc hw0205.c myvector.o -lm -o hw0205
	gcc hw0206.c -lm -o hw0206
clean:
	rm -f *.o
	rm -f hw0201
	rm -f hw0202
	rm -f hw0203
	rm -f hw0204
	rm -f hw0205
	rm -f hw0206