all: mystring.o split.o
	gcc hw0101.c -lm -o hw0101
	gcc hw0102.c -lm -o hw0102
	gcc hw0103.c mystring.o -lm -o hw0103
	gcc hw0104.c mystring.o -lm -o hw0104
	gcc hw0105.c split.o -lm -o hw0105
	gcc hw0106.c -lm -o hw0106
clean:
	rm -f *.o
	rm -f hw0101
	rm -f hw0102
	rm -f hw0103
	rm -f hw0104
	rm -f hw0105
	rm -f hw0106